[versions]
android = "8.1.2"
activity-compose = "1.8.0"
compose-bom = "2023.10.01"
constraintlayout-compose = "1.0.1"
core-ktx = "1.12.0"
libsu = "5.2.0"
core-splashscreen = "1.0.1"
datastore-preferences = "1.0.0"
lifecycle-extensions = "2.2.0"
lifecycle-runtime-ktx = "2.6.2"
material-icons-extended = "1.5.4"
navigation-compose = "2.7.5"
org-jetbrains-kotlin-android = "1.9.20-Beta"
io-github-Rosemoe-sora-editor = "0.22.2"
com-github-skydoves = "1.0.5"
r8 = "8.1.56"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
# Jetpack Compose
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
# Androidx Library
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayout-compose" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore-preferences" }
androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycle-extensions" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material-icons-extended" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
# Kotlin Reflect Library
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "org-jetbrains-kotlin-android" }
# Su process and file-system
libsu-core = { module = "com.github.topjohnwu.libsu:core", version.ref = "libsu" }
# Sora Editor Library
sora-editor-bom = { module = "io.github.Rosemoe.sora-editor:bom", version.ref = "io-github-Rosemoe-sora-editor" }
sora-editor-editor = { module = "io.github.Rosemoe.sora-editor:editor" }
colorpicker-compose = { module = "com.github.skydoves:colorpicker-compose", version.ref = "com-github-skydoves" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "android" }
com-android-library = { id = "com.android.library", version.ref = "android" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }

[bundles]
